### ISSUE TITLE
Hi, are you banned on discord? Are you ok?

### ISSUE THREAD

**Issue by jackowski626** [YXHYX/bingus-fighter#1]

**Comment by YXHYX** [comment]
yes, i was banned for doing awful things, inciting hate amongst communities, encouraging violence (which were all in shitpost channels btw) or maybe because i joined a server that promotes such (was like a nazi server, was there just for the video edits)
so after the ban, i realised how much time was wasted into discord, trying now to change and maybe learn new things hopefully

**Comment by YXHYX** [comment]
and yes. i am ok thanks to god, what about you?

**Comment by jackowski626** [comment]
All good, glad to hear

**Comment by YXHYX** [comment]
need to finish bingus fighter
